### ISSUE TITLE
Error in read_analysis.py

### ISSUE THREAD

**Issue by WeijiaSu** [bcgsc/NanoSim#104]
Hi,
I am trying to use the "read_analysis.py genome" and I keep getting this error, it seems that the get_primary_sam.py has some problem with the HTSeq: 

Traceback (most recent call last):
  File "/anaconda3/bin/read_analysis.py", line 552, in <module>
    main()
  File "/anaconda3/bin/read_analysis.py", line 416, in main
    alnm_ext, unaligned_length, strandness = align_genome(in_fasta, prefix, aligner, num_threads, g_alnm, ref_g)
  File "/anaconda3/bin/read_analysis.py", line 160, in align_genome
    unaligned_length, strandness = get_primary_sam.primary_and_unaligned(g_alnm, prefix)
  File "/gpfs/fs1/anaconda3/bin/get_primary_sam.py", line 15, in primary_and_unaligned
    for alnm in alignments:
  File "/anaconda3/lib/python3.7/site-packages/HTSeq/__init__.py", line 854, in __iter__
    yield SAM_Alignment.from_pysam_AlignedSegment(pa, self.sf)
  File "python3/src/HTSeq/_HTSeq.pyx", line 1379, in HTSeq._HTSeq.SAM_Alignment.from_pysam_AlignedSegment
AttributeError: 'NoneType' object has no attribute 'encode'

Thanks for your help.
Weijia

**Comment by cheny19** [comment]
Hi Weijia,

Could provide the command you used, the log file, and the version of NanoSim you used? It's hard to tell what's the problem simply with this error message.

Thanks,
Chen

**Comment by kmnip** [comment]
The latest code in the master branch contains a bug fix for this issue, which uses pysam (instead of HTSeq) for reading SAM format files.
