### ISSUE TITLE
Training model failure

### ISSUE THREAD

**Issue by abayega** [bcgsc/NanoSim#11]
Hi,

I run the scripts as;

read_analysis.py -i C002_05_6_50kb_TemplateFail.fasta -r E_coli_K12_NC000913.1.fasta

simulator.py circular -r E_coli_K12_NC000913.1.fasta -n 200000 --max_len 200000

and I get the following errors;

2017-02-01 20:24:49: Read pre-process and unaligned reads analysis
2017-02-01 20:24:51: Alignment with LAST
2017-02-01 20:36:07: Aligned reads analysis
2017-02-01 20:36:08: match and error models
2017-02-01 20:36:34: Model fitting
2017-02-01 20:41:16: Finished!
Traceback (most recent call last):
  File "/gs/project/wst-164-ab/anthony/software/NanoSim-master/src/simulator.py", line 671, in <module>
    main()
  File "/gs/project/wst-164-ab/anthony/software/NanoSim-master/src/simulator.py", line 663, in main
    read_profile(number, model_prefix, perfect, max_readlength, min_readlength)
  File "/gs/project/wst-164-ab/anthony/software/NanoSim-master/src/simulator.py", line 129, in read_profile
    with open(model_profile, 'r') as mod_profile:
IOError: [Errno 2] No such file or directory: 'training_model_profile'

Could you kindly help me understand what the problem is.

Thanks

**Comment by cheny19** [comment]
Thanks for pointing this out. It is a bug and it's now fixed. Please try it again and let me know how it works.

**Comment by abayega** [comment]
Everything works fine now, thanks.
