### ISSUE TITLE
metagenome mode error

### ISSUE THREAD

**Issue by dhcai21** [bcgsc/NanoSim#118]
Dear author,

I am using the metagenome mode (3.0.0 version) to generate the metagenome data. However, I encountered the following errors:
Process Process-56:
Traceback (most recent call last):
  File "/Users/caidehan/anaconda3/envs/nanopore/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/Users/caidehan/anaconda3/envs/nanopore/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/caidehan/anaconda3/envs/nanopore/bin/simulator.py", line 800, in simulation_aligned_metagenome
    species_pool = assign_species(ref_lengths, remaining_segments, current_species_bases)
  File "/Users/caidehan/anaconda3/envs/nanopore/bin/simulator.py", line 734, in assign_species
    available_species = [s for s, q in base_quota.items()
  File "/Users/caidehan/anaconda3/envs/nanopore/bin/simulator.py", line 735, in <listcomp>
    if q - length_list_sorted[length_list_pointer] > 0]
**IndexError: list index out of range**
2021-05-18 12:36:27: Start simulation of random reads
2021-05-18 12:36:31: Number of reads simulated >> 2300
2021-05-18 12:36:32: Finished!

The command I used is:
`simulator.py metagenome -gl ./1_div/2metagenome_list -a 2abundance_list.tsv -dl 2dna_type_list.tsv -c ./pre-trained_models/metagenome_ERR3152364_Even/training -o ./1_div/2strains/simulated -max 3000 -min 100 --fastq -t 8 -b albacore`

Could you please help me fix the problem?
Thanks!
Dehan

**Comment by cheny19** [comment]
Hi @dhcai21 , 

Thanks for reporting this. It seems there's a bug when dealing with `-max` and `-min`! I have fixed it and please use the latest commit on Github to see how it goes.

Thanks,
Chen

**Comment by dhcai21** [comment]
Hi @cheny19 ,

The newest version works normally now. Thank you very much!

Dehan
