### ISSUE TITLE
Multithreading bug when using log-normal sampling

### ISSUE THREAD

**Issue by 2tony2** [bcgsc/NanoSim#164]
Hi there!

I was running some simulations today with nanosim until I stumbled upon some issue that I thought may be worth pointing out here.

First of all, I was using a custom trained model and was using the `min` `max` `med` and `sd` option in simulatory.py genome mode as follows:

`simulator.py genome -rg test.fa -c "nanosim_model/testmodel" -n 228 -b "guppy" -s "0.5" -dna_type "linear" -t "8" --fastq -k 6 -t 1 -o "simulated/out.fastq --perfect -min $sequence_min -max $sequence_max -med $sequence_length -sd 0.1`

From my understanding of the source code, this samples fragment size from a log-normal distribution rather than kernel learned from data which had more desirable properties for my task at hand.

Now I was having it work at 1 and 100 reads but not 1000. After some testing the limit seemed to be 228. With the following error popping up when trying 229 reads on 8 threads:

> Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ubuntu/miniconda3/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ubuntu/miniconda3/bin/simulator.py", line 1169, in simulation_aligned_genome
    np.random.lognormal(np.log(median_l), sd_l, remaining_segments)
  File "mtrand.pyx", line 3015, in numpy.random.mtrand.RandomState.lognormal
  File "_common.pyx", line 598, in numpy.random._common.cont
ValueError: maximum supported dimension for an ndarray is 32, found 33

From my interpretation of this the following seems to happen: When sampling from log-normal, an ndarray is used in each thread which has a limit of 32 numbers. Specified threads - 1 are used for this process thus in this case this is 7 threads. This means that 228 reads are divided over 7 threads in ndarrays = ±32 which is around the ndarray limit. I tested with some different thread counts and this hypothesis seems to hold up.

I'm no expert at programming multithreaded applications with numpy so I do not know if this has a straightforward solution, but I just wanted to point this out so you are aware.  [Maybe this could help](https://stackoverflow.com/questions/12668027/good-ways-to-expand-a-numpy-ndarray)?

**Comment by 2tony2** [comment]
Yes I did use it without the `min` `max` `med` and `sd` option but for this specific dataset, some references used it will hang for some. I think this is because I trained the model on some data which produces a read length distribution range which is outside of the range of some references being tested. From looking at the code, my hunch is that the while loop will keep running forever as the major for loop within it is exhausted without saturating the condition. Ideally you'd want to include some sort of exception if your for loop is exhausted to point this out.

I'm not sure whether I tried this specific configuration without the `--perfect` option, I can give it a try but this does seem specifically like a threading issue.
