### ISSUE TITLE
simulator.py genome  FileNotFoundError: [Errno 2] No such file or directory: 'training_model_profile'

### ISSUE THREAD

**Issue by MAXINELSX** [bcgsc/NanoSim#194]
https://github.com/bcgsc/NanoSim/issues/11#issue-204760214 This bug happened again:
(nanosim_env) lishuxian@tong1:/mnt/md0/LSX/lishuxian/lishuxian/mag/LSX-isolates/Kleb-for-lsx/bin-file$ cat list.fasta.txt  | while read line; do /mnt/md0/LSX/lishuxian/lishuxian/mag/LSX-isolates/Kleb-for-lsx/bin-file/NanoSim/src/simulator.py  genome --fastq -rg filtered_${line}.fasta -b guppy -n 100000 -t  40  -s 1 ; done

running the code with following parameters:

ref_g filtered_manhole-barcode47-bin.fasta
model_prefix training
out simulated
number [100000]
perfect False
kmer_bias None
basecaller guppy
dna_type linear
strandness 1.0
sd_len None
median_len None
max_len inf
min_len 50
fastq True
chimeric False
num_threads 40
2023-08-14 23:17:28: /mnt/md0/LSX/lishuxian/lishuxian/mag/LSX-isolates/Kleb-for-lsx/bin-file/NanoSim/src/simulator.py genome --fastq -rg filtered_manhole-barcode47-bin.fasta -b guppy -n 100000 -t 40 -s 1
2023-08-14 23:17:28: Read in reference 
2023-08-14 23:17:28: Read error profile
Traceback (most recent call last):
  File "/mnt/md0/LSX/lishuxian/lishuxian/mag/LSX-isolates/Kleb-for-lsx/bin-file/NanoSim/src/simulator.py", line 2433, in <module>
    main()
  File "/mnt/md0/LSX/lishuxian/lishuxian/mag/LSX-isolates/Kleb-for-lsx/bin-file/NanoSim/src/simulator.py", line 2194, in main
    read_profile(ref_g, number, model_prefix, perfect, args.mode, strandness, dna_type=dna_type, chimeric=chimeric)
  File "/mnt/md0/LSX/lishuxian/lishuxian/mag/LSX-isolates/Kleb-for-lsx/bin-file/NanoSim/src/simulator.py", line 474, in read_profile
    with open(model_profile, 'r') as mod_profile:
FileNotFoundError: [Errno 2] No such file or directory: 'training_model_profile'

**Comment by SaberHQ** [comment]
Hey @MAXINELSX 

I am so sorry for this late reply. I have no idea why I missed your comment/issue. 

First, make sure you are using the latest committed version. The error you posted is a `FileNotFoundError` meaning that NanoSim couldn't find the location of the model profiles. Are you using the pre-trained models? If so, clearly state the directory of the pre-trained models to be used in the simulation stage. You could also train your own model using the [read_analysis.py](https://github.com/bcgsc/NanoSim/blob/master/src/read_analysis.py) script. Refer to the readme file for comprehensive information.

**Comment by lcoombe** [comment]
Closing old issues - please feel free to open a new issue if you have further questions!
