### ISSUE TITLE
Issue of shortening the simulation time

### ISSUE THREAD

**Issue by HLHsieh** [bcgsc/NanoSim#210]
Hi there,

Thank you for developing this handy tool; I've been using it for a long time. Recently, I wanted to perform a more challenging test on my tool by adjusting the read length of the simulated reads as follows:

```
simulator.py genome -rg test.fasta -c /home/hsinlun/bin/NanoSim/pre-trained_models/human_giab_hg002_sub1M_kitv14_dorado/hg002_nanosim_sub1M -t 24 -med 10000 -sd 1000 -n 27737 -o test_2x --seed 100 -b guppy
```

However, it took about five days and still failed. I noticed that it got stuck at the simulation step. I then tried the following command, which completed the entire process in just 10 minutes:

```
simulator.py genome -rg test.fasta -c /home/hsinlun/bin/NanoSim/pre-trained_models/human_giab_hg002_sub1M_kitv14_dorado/hg002_nanosim_sub1M -t 24 -n 27737 -o test_2x --seed 100 -b guppy
```

I am seeking your suggestions for optimizing my workflow. Additionally, is there any parameter or recommendation for controlling the mean read length instead of the median?

Best regards,
Hsin

**Comment by kmnip** [comment]
I think your simulation is stuck in an infinite loop here:
https://github.com/bcgsc/NanoSim/blob/master/src/simulator.py#L1237
It is trying to simulate certain read lengths, but it cannot find the "suitable" combination of lengths for the unaligned head/tail and the aligned segments.

Can you add the `--perfect` flag to your command? Basically, it simulates perfect reads. I just want see whether it gets stuck (i.e. running longer than 10 minutes), too.

**Comment by kmnip** [comment]
@HLHsieh , please checkout the changes in my branch:
https://github.com/bcgsc/NanoSim/tree/kmnip_patch1
It may potentially handle the infinite loop. This is not an ideal solution, but the user is informed of the issue at the very least.
@SaberHQ , what do you think?

**Comment by HLHsieh** [comment]
Hi @kmnip,

Thank you for your suggestions. First, I tried to add `--perfect` to my command, but it got error:

```
Process Process-2:
Traceback (most recent call last):
  File "/nfs/turbo/umms-kinfai/hsinlun/miniconda3/envs/nanosim/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/nfs/turbo/umms-kinfai/hsinlun/miniconda3/envs/nanosim/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/home/hsinlun/bin/NanoSim/src/simulator.py", line 1240, in simulation_aligned_genome
    np.random.lognormal(np.log(median_l), sd_l, remaining_segments)
  File "mtrand.pyx", line 3015, in numpy.random.mtrand.RandomState.lognormal
  File "_common.pyx", line 598, in numpy.random._common.cont
ValueError: maximum supported dimension for an ndarray is 32, found 357424
Process Process-3:
Traceback (most recent call last):
  File "/nfs/turbo/umms-kinfai/hsinlun/miniconda3/envs/nanosim/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/nfs/turbo/umms-kinfai/hsinlun/miniconda3/envs/nanosim/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/home/hsinlun/bin/NanoSim/src/simulator.py", line 1240, in simulation_aligned_genome
    np.random.lognormal(np.log(median_l), sd_l, remaining_segments)
  File "mtrand.pyx", line 3015, in numpy.random.mtrand.RandomState.lognormal
  File "_common.pyx", line 598, in numpy.random._common.cont
ValueError: maximum supported dimension for an ndarray is 32, found 357424
Process Process-8:
Traceback (most recent call last):
  File "/nfs/turbo/umms-kinfai/hsinlun/miniconda3/envs/nanosim/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/nfs/turbo/umms-kinfai/hsinlun/miniconda3/envs/nanosim/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/home/hsinlun/bin/NanoSim/src/simulator.py", line 1240, in simulation_aligned_genome
    np.random.lognormal(np.log(median_l), sd_l, remaining_segments)
  File "mtrand.pyx", line 3015, in numpy.random.mtrand.RandomState.lognormal
  File "_common.pyx", line 598, in numpy.random._common.cont
ValueError: maximum supported dimension for an ndarray is 32, found 357426
Process Process-1:
Traceback (most recent call last):
  File "/nfs/turbo/umms-kinfai/hsinlun/miniconda3/envs/nanosim/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/nfs/turbo/umms-kinfai/hsinlun/miniconda3/envs/nanosim/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/home/hsinlun/bin/NanoSim/src/simulator.py", line 1240, in simulation_aligned_genome
    np.random.lognormal(np.log(median_l), sd_l, remaining_segments)
  File "mtrand.pyx", line 3015, in numpy.random.mtrand.RandomState.lognormal
  File "_common.pyx", line 598, in numpy.random._common.cont
ValueError: maximum supported dimension for an ndarray is 32, found 357424
Process Process-7:
Traceback (most recent call last):
  File "/nfs/turbo/umms-kinfai/hsinlun/miniconda3/envs/nanosim/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/nfs/turbo/umms-kinfai/hsinlun/miniconda3/envs/nanosim/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/home/hsinlun/bin/NanoSim/src/simulator.py", line 1240, in simulation_aligned_genome
    np.random.lognormal(np.log(median_l), sd_l, remaining_segments)
  File "mtrand.pyx", line 3015, in numpy.random.mtrand.RandomState.lognormal
  File "_common.pyx", line 598, in numpy.random._common.cont
ValueError: maximum supported dimension for an ndarray is 32, found 357424
Process Process-4:
Traceback (most recent call last):
  File "/nfs/turbo/umms-kinfai/hsinlun/miniconda3/envs/nanosim/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/nfs/turbo/umms-kinfai/hsinlun/miniconda3/envs/nanosim/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/home/hsinlun/bin/NanoSim/src/simulator.py", line 1240, in simulation_aligned_genome
    np.random.lognormal(np.log(median_l), sd_l, remaining_segments)
  File "mtrand.pyx", line 3015, in numpy.random.mtrand.RandomState.lognormal
  File "_common.pyx", line 598, in numpy.random._common.cont
ValueError: maximum supported dimension for an ndarray is 32, found 357424
Process Process-5:
Traceback (most recent call last):
  File "/nfs/turbo/umms-kinfai/hsinlun/miniconda3/envs/nanosim/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/nfs/turbo/umms-kinfai/hsinlun/miniconda3/envs/nanosim/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/home/hsinlun/bin/NanoSim/src/simulator.py", line 1240, in simulation_aligned_genome
    np.random.lognormal(np.log(median_l), sd_l, remaining_segments)
  File "mtrand.pyx", line 3015, in numpy.random.mtrand.RandomState.lognormal
  File "_common.pyx", line 598, in numpy.random._common.cont
ValueError: maximum supported dimension for an ndarray is 32, found 357424
Process Process-6:
Traceback (most recent call last):
  File "/nfs/turbo/umms-kinfai/hsinlun/miniconda3/envs/nanosim/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/nfs/turbo/umms-kinfai/hsinlun/miniconda3/envs/nanosim/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/home/hsinlun/bin/NanoSim/src/simulator.py", line 1240, in simulation_aligned_genome
    np.random.lognormal(np.log(median_l), sd_l, remaining_segments)
  File "mtrand.pyx", line 3015, in numpy.random.mtrand.RandomState.lognormal
  File "_common.pyx", line 598, in numpy.random._common.cont
ValueError: maximum supported dimension for an ndarray is 32, found 357424

2024-07-12 14:56:04: Finished!
```
When the `--perfect` flag was removed, the error did not occur but stuck somewhere.

Secondly, I applied the latest script which was changed two days ago.

Here is the log:
```
Simulated 356652 `aligned` reads...s simulated >> 2260001
Simulated 356652 `aligned` reads...s simulated >> 2270001
Simulated 356652 `aligned` reads...s simulated >> 2300001
Simulated 356654 `aligned` reads...s simulated >> 2330001
Simulated 356652 `aligned` reads...
```
But, it was still stuck until the time limit.



Best,
Hsin-Lun

**Comment by SaberHQ** [comment]
Thank you @HLHsieh for your interest in using NanoSim and reporting this issue and thank you @kmnip for your solution. 

I am currently away from work with limited access to internet. I will look into it deeper once I return in about 2 weeks. For now, what I can say is that the root of the problem (based on your log file provided) comes down to the following line of the code:

`np.random.lognormal(np.log(median_l), sd_l, remaining_segments)`

Where it tries to create an array with X (X here is the number of sequences you are trying to simulate, say 27,737 as in your first post) log-normally distributed samples based on a median of 10,000 and a standard deviation of 2 (based on your first post).

From what I see, the problem does not look like an infinite loop, it is rather related to the NumPy function and I suspect that it might be an environment and version issue. It could be that there is a memory limitation or a bug in the version of NumPy you are using. Ensure that you are using a recent version of NumPy and that your environment has sufficient memory available. (You can update NumPy using pip install NumPy --upgrade.) It could also be a memory problem since creating a huge NumPy array might break your code. Make sure your system isn’t running out of memory when this operation is performed.

To further look into it, if you are comfortable with Python coding, write a print function just before line 1239 to check the values for `median_l`, `sd_l`, and `remaining_segments`.

Now, there is obviously room for improvement on the code to avoid such problems and I might look into this once I have free time as I mentioned earlier. Since the log file you created does not contain Warning messages Ka Ming incorporated in the patch mode, I suspect again that it is not a infinite loop problem (At least by looking into the log file you just provided). 

Thanks and I will keep you updated.

**Comment by HLHsieh** [comment]
Hi @SaberHQ ,

Thank you for taking the time to look into my issue. Additionally, I found something strange. I executed the previous `simulator.py` today around 12pm, and the following are the output files:

```
-rw-rw-r-- 1 hsinlun kinfai_root 929996253 Jul 12 12:03 test_2x_aligned_reads0.fasta
-rw-rw-r-- 1 hsinlun kinfai_root 929370674 Jul 12 12:03 test_2x_aligned_reads1.fasta
-rw-rw-r-- 1 hsinlun kinfai_root 932867870 Jul 12 12:03 test_2x_aligned_reads2.fasta
-rw-rw-r-- 1 hsinlun kinfai_root 931018020 Jul 12 12:03 test_2x_aligned_reads3.fasta
-rw-rw-r-- 1 hsinlun kinfai_root 930458715 Jul 12 12:03 test_2x_aligned_reads4.fasta
-rw-rw-r-- 1 hsinlun kinfai_root 541488149 Jul 12 12:00 test_2x_aligned_reads5.fasta
-rw-rw-r-- 1 hsinlun kinfai_root 931178341 Jul 12 12:03 test_2x_aligned_reads6.fasta
-rw-rw-r-- 1 hsinlun kinfai_root 932068207 Jul 12 12:03 test_2x_aligned_reads7.fasta
-rw-rw-r-- 1 hsinlun kinfai_root 587778206 Jul 12 12:03 test_2x_error_profile0
-rw-rw-r-- 1 hsinlun kinfai_root 587177640 Jul 12 12:03 test_2x_error_profile1
-rw-rw-r-- 1 hsinlun kinfai_root 588649987 Jul 12 12:03 test_2x_error_profile2
-rw-rw-r-- 1 hsinlun kinfai_root 587296727 Jul 12 12:03 test_2x_error_profile3
-rw-rw-r-- 1 hsinlun kinfai_root 588038704 Jul 12 12:03 test_2x_error_profile4
-rw-rw-r-- 1 hsinlun kinfai_root 341204833 Jul 12 12:00 test_2x_error_profile5
-rw-rw-r-- 1 hsinlun kinfai_root 587499390 Jul 12 12:03 test_2x_error_profile6
-rw-rw-r-- 1 hsinlun kinfai_root 589159695 Jul 12 12:03 test_2x_error_profile7
```

After executing for 6 hours, there were no changes to these files. I am wondering whether I can merge these files on my own to create the final fasta file.

Best,
Hsin
