### ISSUE TITLE
not python>=2.6 compatible

### ISSUE THREAD

**Issue by nick-youngblut** [bcgsc/NanoSim#25]
The `README.md` for `nanosim` states:

> Python (2.6 or above) 

Thus, `nanosim` should be compatible with Python>=2.6 and Python>=3. However, when using `nanosim v1.3.0`, I got the following error:

```
Traceback (most recent call last):
  File "/ebio/abt3_projects/software/dev/miniconda3_dev/envs/read_sim/bin/simulator.py", line 716, in <module>
    main()
  File "/ebio/abt3_projects/software/dev/miniconda3_dev/envs/read_sim/bin/simulator.py", line 708, in main
    read_profile(number, model_prefix, perfect, max_readlength, min_readlength)
  File "/ebio/abt3_projects/software/dev/miniconda3_dev/envs/read_sim/bin/simulator.py", line 148, in read_profile
    match_ht_list = read_ecdf(fm_profile)
  File "/ebio/abt3_projects/software/dev/miniconda3_dev/envs/read_sim/bin/simulator.py", line 79, in read_ecdf
    for i in xrange(lanes):
NameError: name 'xrange' is not defined
```

...which suggests that the code is not actually python>=3 compatible.  It would help to clarify the README or update the python code. Also, the [bioconda recipe for nanosim](https://github.com/bioconda/bioconda-recipes/blob/master/recipes/nanosim/meta.yaml) should specify `python>=2.6`.

**Comment by nick-youngblut** [comment]
I just saw that `xrange` is imported from the `six` package. So, the actual problem is that the bioconda recipe doesn't include the `six` package dependency. Also, it appears that this dependency isn't listed in the README for `nanosim`
