### ISSUE TITLE
[IndexError: string index out of range] Trying to introduce errors at indices > length of read

### ISSUE THREAD

**Issue by baraaorabi** [bcgsc/NanoSim#58]
NanoSim is occusionally producing an error caused by the generating a `ref_l` greater than the length of a reference contig. In this example, my reference has only one contig of length ~850. Note that I added two lines to print the `error_dict` and `new_read` variables for debugging.

```
[borabi@xavier3 freddie]$ simulator.py linear -r reference.fasta -c training -o simulated -n 3
len(new_read)
851
error_dict:
{13: ['del', 1], 22.5: ['ins', 4], 48: ['mis', 1], 52: ['mis', 1], 53: ['mis', 1], 134: ['del', 1], 147: ['del', 1], 165: ['mis', 1], 166: ['mis', 1], 177: ['del', 1], 228: ['mis', 1], 229: ['mis', 1], 237.5: ['ins', 1], 246: ['mis', 1], 250: ['mis', 1], 265: ['del', 1], 288: ['del', 1], 310: ['del', 1], 337: ['mis', 1], 370: ['del', 1], 371: ['mis', 2], 494: ['del', 1], 507.5: ['ins', 3], 521: ['mis', 1], 531.5: ['ins', 5], 535.5: ['ins', 3], 573: ['del', 3], 577: ['del', 1], 578.5: ['ins', 1], 590: ['del', 3], 615: ['mis', 2], 618: ['del', 1], 638: ['del', 1], 671: ['mis', 1], 674: ['mis', 2], 699: ['del', 2], 701: ['mis', 1], 752: ['del', 2], 754: ['mis', 2], 756.5: ['ins', 1], 759: ['mis', 1], 763: ['mis', 1], 770: ['mis', 1], 775: ['mis', 2], 778: ['mis', 1], 782: ['del', 1], 810: ['mis', 1], 819.5: ['ins', 2], 845.5: ['ins', 2], 870: ['mis', 1], 890: ['del', 2], 909: ['del', 1], 928: ['del', 2], 942.5: ['ins', 2], 943.5: ['ins', 2], 974: ['mis', 1], 983: ['del', 3], 996.5: ['ins', 1], 1018: ['mis', 1], 1054: ['mis', 2], 1067: ['del', 1], 1072: ['del', 3], 1078: ['mis', 1], 1090: ['mis', 1], 1104.5: ['ins', 3], 1107: ['mis', 1], 1122: ['del', 1], 1125: ['mis', 2], 1127: ['mis', 2], 1130: ['mis', 2], 1132: ['mis', 1], 1136: ['del', 2], 1149: ['del', 2], 1153: ['del', 1], 1163: ['mis', 1], 1170.5: ['ins', 1], 1211.5: ['ins', 2], 1212: ['mis', 1], 1214: ['del', 1], 1215: ['mis', 1], 1223: ['del', 1], 1233: ['mis', 1], 1258: ['mis', 1], 1291: ['mis', 1], 1299: ['mis', 1], 1303.5: ['ins', 1], 1305: ['mis', 2], 1310.5: ['ins', 4], 1314: ['mis', 1], 1316: ['del', 1], 1322.5: ['ins', 2], 1341.5: ['ins', 1], 1358: ['del', 1]}
Traceback (most recent call last):
  File "simulator.py", line 741, in <module>
    main()
  File "simulator.py", line 735, in main
    max_readlength, min_readlength)
  File "simulator.py", line 384, in simulation
    read_mutated = mutate_read(new_read, new_read_name, out_error, error_dict, kmer_bias)
  File "simulator.py", line 581, in mutate_read
    tmp_bases.remove(read[key + i])
IndexError: string index out of range

```

**Comment by cheny19** [comment]
Hi @baraaorabi, thanks for reporting this. This bug has been raised by other users as well. Right now we're working on the new release, which will probably be done within this week or early next. Stay tuned.

**Comment by SaberHQ** [comment]
Dear @baraaorabi please try the new release. I am closing this issue for now. If you encounter any problem, let us know.
