### ISSUE TITLE
problem with dna_type

### ISSUE THREAD

**Issue by lfaino** [bcgsc/NanoSim#59]
dear Developper,
I get this error when i run the tool with this command:
command:
`~/Downloads/NanoSim/src/simulator.py genome -dna_type linear -rg Fusve2_AssemblyScaffolds.fasta -c training`

error:
`running the code with following parameters:

ref_g Fusve2_AssemblyScaffolds.fasta
model_prefix training
out simulated
number 20000
perfect False
kmer_bias 0
dna_type linear
strandness None
sd_readlength None
median_readlength None
2019-05-21 08:25:33: /home/lfaino/Downloads/NanoSim/src/simulator.py genome -dna_type linear -rg Fusve2_AssemblyScaffolds.fasta -c training
mkdir: missing operand
Try 'mkdir --help' for more information.
2019-05-21 08:25:33: Read in reference
Traceback (most recent call last):
  File "/home/lfaino/Downloads/NanoSim/src/simulator.py", line 1184, in <module>
    main()
  File "/home/lfaino/Downloads/NanoSim/src/simulator.py", line 1123, in main
    read_profile(ref_g, None, number, model_prefix, perfect, args.mode, strandness)
  File "/home/lfaino/Downloads/NanoSim/src/simulator.py", line 281, in read_profile
    if len(seq_dict) > 1 and dna_type == "circular":
NameError: global name 'dna_type' is not defined`

**Comment by cheny19** [comment]
Hi @lfaino,

I guess you are using the latest commit, instead of the latest released version? There're some bugs with this commit, and we are working on resolving them to make a new release.

Thanks,
Chen

**Comment by SaberHQ** [comment]
Dear @lfaino Were you able to make it run with the newest release?

https://github.com/bcgsc/NanoSim/releases

let us know if it works or not and we can close this issue then.
