### ISSUE TITLE
cannot import name 'joblib' from 'sklearn.externals'

### ISSUE THREAD

**Issue by cytham** [bcgsc/NanoSim#85]
I encountered this error while running read_analysis.py:

Traceback (most recent call last):
  File "$home/miniconda3/envs/test/bin/read_analysis.py", line 22, in <module>
    import head_align_tail_dist as align
  File "$home/miniconda3/envs/test/bin/head_align_tail_dist.py", line 7, in <module>
    from sklearn.externals import joblib
ImportError: cannot import name 'joblib' from 'sklearn.externals' ($home/miniconda3/envs/test/lib/python3.7/site-packages/sklearn/externals/__init__.py)

Some info:
Installed NanoSim using conda
Python version 3.7.7
sklearn version 0.23.1

**Comment by cheny19** [comment]
Could you try to change that line in `head_align_tail_dist.py` to `import joblib`, and see if it still occurs? This problem occurred with other users when using `simulator.py` as well. It seems certain versions of the joblib package and scikit-learn are not very compatible. We will update our release asap as well.

**Comment by cytham** [comment]
That worked. Actually, the error I showed above was after changing the joblib import for read_analysis.py (was playing around with it and forgot to change it back). Hence, both the joblib imports in read_analysis.py and head_align_tail_dist.py has to be changed in order for it to work for me.

Thanks

**Comment by cytham** [comment]
I encountered another error when running read_analysis.py.

2020-06-17 09:50:25: Processing alignment file: sam
Traceback (most recent call last):
  File "$home/miniconda3/envs/test/bin/read_analysis.py", line 553, in <module>
    main()
  File "$home/miniconda3/envs/test/bin/read_analysis.py", line 417, in main
    alnm_ext, unaligned_length, strandness = align_genome(in_fasta, prefix, aligner, num_threads, g_alnm, ref_g)
  File "$home/miniconda3/envs/test/bin/read_analysis.py", line 161, in align_genome
    unaligned_length, strandness = get_primary_sam.primary_and_unaligned(g_alnm, prefix)
  File "$home/miniconda3/envs/test/bin/get_primary_sam.py", line 15, in primary_and_unaligned
    for alnm in alignments:
  File "$home/miniconda3/envs/test/lib/python3.7/site-packages/HTSeq/__init__.py", line 854, in __iter__
    yield SAM_Alignment.from_pysam_AlignedSegment(pa, self.sf)
  File "python3/src/HTSeq/_HTSeq.pyx", line 1379, in HTSeq._HTSeq.SAM_Alignment.from_pysam_AlignedSegment
AttributeError: 'NoneType' object has no attribute 'encode'

Seems like a bug with HTSeq, any idea how to solve it? Thanks

**Comment by cytham** [comment]
I encountered another error:

2020-06-17 17:52:59: Read pre-process
2020-06-17 17:53:03: Processing alignment file: sam
2020-06-17 17:54:58: Aligned reads analysis
Traceback (most recent call last):
  File "$home/miniconda3/envs/test/bin/read_analysis.py", line 553, in <module>
    main()
  File "$home/miniconda3/envs/test/bin/read_analysis.py", line 421, in main
    num_aligned = align.head_align_tail(prefix, alnm_ext, args.mode)
  File "$home/miniconda3/envs/test/bin/head_align_tail_dist.py", line 105, in head_align_tail
    for alnm in alignments:
  File "$home/miniconda3/envs/test/lib/python3.7/site-packages/HTSeq/__init__.py", line 851, in __iter__
    self.sf = pysam.AlignmentFile(self.filename, "r", check_sq=self.check_sq)
  File "pysam/libcalignmentfile.pyx", line 741, in pysam.libcalignmentfile.AlignmentFile.__cinit__
  File "pysam/libcalignmentfile.pyx", line 990, in pysam.libcalignmentfile.AlignmentFile._open
ValueError: file has no sequences defined (mode='r') - is it SAM/BAM format? Consider opening with check_sq=False

After some investigation, I believe the problem lies with an empty training_primary.sam file which is caused by the get_primary_sam.py script, where "alnm.original_sam_line" returns empty.

Please help with this issue. Thanks

**Comment by cheny19** [comment]
Yes, it seems like you provided your own sam file alignment and the extracted primary alignment file is empty. Could you double check your own sam file and see if it's correct?

**Comment by cytham** [comment]
I don't see any problem with my own sam file. I generated it using minimap2 with the --MD and -ax map-ont options and then pipe it to samtools with -F 256 filter to remove not-primary alignments as they will result in an error with HTSeq in your pipeline as there is no query.sequence for these alignments, resulting in the 'NoneType' object has no attribute 'encode' error (See below).

Also, when allowing nanosim to do own mapping, the sam file it produces have not-primary alignments which resulted in the "'NoneType' object has no attribute 'encode'" (See below). 

I have used nanosim many times in the past to simulate genomic ONT reads with no issue. I am not sure why I am encountering so many problems now.

Traceback (most recent call last):
  File "$home/miniconda3/envs/test/bin/read_analysis.py", line 553, in <module>
    main()
  File "$home/miniconda3/envs/test/bin/read_analysis.py", line 417, in main
    alnm_ext, unaligned_length, strandness = align_genome(in_fasta, prefix, aligner, num_threads, g_alnm, ref_g)
  File "$home/miniconda3/envs/test/bin/read_analysis.py", line 161, in align_genome
    unaligned_length, strandness = get_primary_sam.primary_and_unaligned(g_alnm, prefix)
  File "$home/miniconda3/envs/test/bin/get_primary_sam.py", line 15, in primary_and_unaligned
    for alnm in alignments:
  File "$home/miniconda3/envs/test/lib/python3.7/site-packages/HTSeq/__init__.py", line 854, in __iter__
    yield SAM_Alignment.from_pysam_AlignedSegment(pa, self.sf)
  File "python3/src/HTSeq/_HTSeq.pyx", line 1379, in HTSeq._HTSeq.SAM_Alignment.from_pysam_AlignedSegment
AttributeError: 'NoneType' object has no attribute 'encode'

**Comment by cheny19** [comment]
I'm sorry about all the trouble. I'm busy with other projects recently, and my colleague will investigate into this issue further. We will update you in a few days.

**Comment by cytham** [comment]
I managed to run read_analysis.py by downgrading HTSeq from v0.12.4 to v0.10.0. Hence i believe that all the problems arose from HTSeq updates.

I have some suggestions for NanoSim to be compatible with the updated HTSeq, please refer to #88.
But do note that we need to wait for HTSeq to fix https://github.com/htseq/htseq/issues/11 before it can be further tested.

**Comment by cheny19** [comment]
I see... We are actually working on meta-NanoSim right now, and in that version, we plan to replace HTSeq with Pysam. Hope that will solve the problem as well. Thanks for digging into this problem.
