### ISSUE TITLE
keyError: 0 Simulate.py

### ISSUE THREAD

**Issue by Clement-BIRBES** [bcgsc/NanoSim#97]
Hi, after trying your tools i'm facing an issue with Simulate.py :

running the code with following parameters:

```
ref_g ../Reference.fasta
model_prefix training
out 50X
number 3000
perfect False
kmer_bias 5
basecaller guppy
dna_type linear
strandness None
sd_len None
median_len None
max_len inf
min_len 50
fastq False
num_threads 1
2020-09-11 10:18:18: /usr/local/bioinfo/src/NanoSim/NanoSim-v2.6.0/src/simulator.py genome -rg ../Reference.fasta -o 50X -k 5 -n 3000 -b guppy
2020-09-11 10:18:18: Read in reference
2020-09-11 10:18:19: Read error profile
2020-09-11 10:18:19: Read KDF of unaligned reads
Traceback (most recent call last):
File "/usr/local/bioinfo/src/NanoSim/NanoSim-v2.6.0/src/simulator.py", line 1702, in <module>
    main()
  File "/usr/local/bioinfo/src/NanoSim/NanoSim-v2.6.0/src/simulator.py", line 1599, in main
    read_profile(ref_g, None, number, model_prefix, perfect, args.mode, strandness, None, False, dna_type, None)
  File "/usr/local/bioinfo/src/NanoSim/NanoSim-v2.6.0/src/simulator.py", line 411, in read_profile
    kde_unaligned = joblib.load(model_prefix + "_unaligned_length.pkl")
  File "/tools/python/3.6.3/lib/python3.6/site-packages/joblib/numpy_pickle.py", line 578, in load
    obj = _unpickle(fobj, filename, mmap_mode)
  File "/tools/python/3.6.3/lib/python3.6/site-packages/joblib/numpy_pickle.py", line 508, in _unpickle
    obj = unpickler.load()
  File "/tools/python/3.6.3/lib/python3.6/pickle.py", line 1050, in load
    dispatch[key[0]](self)
KeyError: 0
```

i use python 3.6.3, minimap2 2.11 and nanosim 2.6 with following command line :

simulator.py genome -rg ../Reference.fasta -o 50X -k 5 -n 3000 -b guppy

I tried to run with no option, still the same error
Do you know where this error come from ?

**Comment by SaberHQ** [comment]
Hi @Clement-BIRBES . This issue has been reported by other users in #81 . Could you try from sklearn.externals import joblib instead of import joblib and see if it occurs?

For your information, we are about to release a new version in which we trained all models again using consistent pickle versions. It will solve the import pickle bug.

**Comment by Clement-BIRBES** [comment]
Hi @SaberHQ 
unfortunately that didn't solved 100% of the problem, i now have this error :

Traceback (most recent call last):
  File "/usr/local/bioinfo/src/NanoSim/NanoSim-v2.6.0/src/simulator.py", line 1703, in <module>
    main()
  File "/usr/local/bioinfo/src/NanoSim/NanoSim-v2.6.0/src/simulator.py", line 1606, in main
    fastq, median_len, sd_len)
  File "/usr/local/bioinfo/src/NanoSim/NanoSim-v2.6.0/src/simulator.py", line 989, in simulation
    kmer_bias, basecaller, read_type, fastq, number_aligned, per)
  File "/usr/local/bioinfo/src/NanoSim/NanoSim-v2.6.0/src/simulator.py", line 846, in simulation_aligned_genome
    basecaller, read_type, fastq, kmer_bias)
  File "/usr/local/bioinfo/src/NanoSim/NanoSim-v2.6.0/src/simulator.py", line 1369, in mutate_read
    tmp_bases.remove(read[key + i])
ValueError: list.remove(x): x not in list

**Comment by SaberHQ** [comment]
Hi @Clement-BIRBES The _mutate_read_ function introduces errors (indels and mismatches) into the input sequence according to the error profile. _temp_bases_ is a list of 4 nucleotide characters: ['A', 'T', 'C', 'G']. In that particular line of the code, it tries to remove a nucleotide from index _key+i_ and in following line, it adds a random nucleotide to account for mismatches.

According to my above explanation, it looks like that the input read to that function contains nucleotide characters other than A, T, C, and G. I assume you are simulating genomic reads. Would you please double check and see if your input genome fasta file contains a character other than those four?

Hope I explained it clearly. Please look into that genome fasta file you are using and see if that is the case. Please let me know if you need any help.

**Comment by SaberHQ** [comment]
Dear @Clement-BIRBES , I hope you found my explanation helpful. I am closing this issue. Please feel free to reopen and ask any questions.
